[project]
name = "fpl-data-warehouse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests>=2.32.5",
]

[tool.ruff]
line-length = 100
lint.select = ['E', 'F', 'W', 'A', 'PLC', 'PLE', 'PLW', 'I', 'D']
lint.ignore = [
    'D100',
    'D202',
    'D211',
    'D212',
    'D401'
]

[dependency-groups]
dev = [
    "duckdb>=1.5.2",
    "ruff>=0.15.12",
]
