[project]
name = "fpl-data-warehouse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests>=2.32.5",
]

[dependency-groups]
dev = [
    "dbt-duckdb>=1.10.1",
    "duckdb>=1.5.2",
    "ruff>=0.15.12",
]

[tool.ruff]
line-length = 100
lint.select =  [
    "E",   # pycodestyle errors
    "F",   # pyflakes — undefined variables, unused imports
    "I",   # isort — import ordering
    "UP",  # pyupgrade — modern Python syntax
]
