version: 2

models:
  - name: stg_teams
    description: Staging model for Premier League teams, extracted from bronze
    columns:
      - name: team_id
        description: Primary key for the team
        tests:
          - unique
          - not_null
      - name: full_name
        description: Full name of team
        tests:
          - not_null
      - name: short_name
        description: 3 letter abbreviation of team
        tests:
          - not_null
